### PR TITLE
Expense manager customized ngFormioGrid

### PR DESCRIPTION
**Pull request by rkachhawaha**
Hi Everyone,

Please find the ngFormioGrid code that I customized based on to full-fill the requirements in "Expense Manager" application. Kindly review and provide your feedback.

Thanks,
Ravi

### CODE REVIEW

**Comment by randallknutson** [comment]
Hey Ravi,

It is really hard to tell what was changed here and why. Instead of saying it was customizations for expense manager, can you explain what the customizations were?

Separating the code reformatting into a different commit would help as well.

**Comment by rkachhawaha** [comment]
Hi Randall,
Thanks for reviewing the code.

The ngFormioGrid changes are not actually the expense manager app specific customization. I tried to make code changes in ngFormioGrid in such a way that it should execute as stand alone bower component. I used few functions in "Expense Manager" like "filter Grid Record between two dates" and prepared function in ngFormioGrid which accept two dates (StartDate and EndDate) and return filtered record. I prepared one more function " $scope.exposeGridApi" to expose "GridApi"object. It will simply expose "GridApi" object to use outside of "formio-grid.js". I will do more detailed commenting on code and recommit it for your review further.

Thanks

**Comment by travist** [comment]
This pull request kind of scares me with all of the diffs. I will be bringing some of the row selection items into the master (with the work I am doing with a client) so I am thinking we need to re-merge this once I am done with that endeavor and see how we can make the diff not so intimidating.

**Comment by rkachhawaha** [comment]
Travis, 

Please let me know if you need me to work on modifications of any part of the ngFormioGrid ? so that it should be flexible enough to merge with your code.

Sent from my ASUS

-------- Original Message --------

**Comment by travist** [comment]
I would say for now hold off until I commit my changes I have been making. What I would then like is for you to re-do your changes on top of those. I should be done by the end of this week.

Thanks,

Travis.

**Comment by rkachhawaha** [comment]
Sounds good. 

Thanks,
Ravi 

Sent from my ASUS

-------- Original Message --------

**Comment by randallknutson** [comment]
This is moved to another pull request now.

**Pull request closed without merging**
